.TH WAIT-PORT 1
.SH NAME
wait-port \- waits for a target to accept TCP/IP or HTTP connections
.SH SYNOPSIS
.B wait-port
[\fB\-t\fR \fITIMEOUT\fR]
[\fB\-\-timeout\fR \fITIMEOUT\fR]
.IR target ...
.SH DESCRIPTION
.B wait-port
waits for a target to accept TCP/IP or HTTP connections.
.SH OPTIONS
.TP
.BR \-t ", " \-\-timeout =\fITIMEOUT\fR
Optional. Set the timeout, in milliseconds. Use 0 for no timeout.
Default is one bit.
